### PR TITLE
Add CTCSS support

### PR DESCRIPTION
**Pull request by charlie-foxtrot**

### CODE REVIEW

**Comment by charlie-foxtrot** [comment]
@rough316  Yes, please, any feedback would be appreciated.  There is an issue with `scan` mode not working correctly that I haven't addressed yet.

What I did in this PR is try to re-open the CTCSS support change from before the maintainer transition and to add some unit test coverage.  Unfortunately this led to a lot more refactoring work than I anticipated.

I will likely abandon this PR and do the refactoring and add unit tests to existing modules first, then add the CTCSS support code.  But, in the meantime, this branch should have full CTCSS support (minus scan mode)

**Comment by feelingwalnut** [comment]
I've also a frequency that transmits ownership morse pings every half hour. All of our actual coms have a ctcss tone.

Is there a config option for this?
The version will need compiled?

**Comment by charlie-foxtrot** [comment]
@feelingwalnut yes this will need to be compiled.  if you are already compiling the `main` or `unstable` branch then you can  switch to this branch by doing `git fetch` then `git checkout add_ctcss_support` then compile as before.

config options are setup similar to `notch`, here is a channel config that uses both `ctcss` for the squelch then `notch` to remove that tone from the audio:

```
      {
        freq = 153.90500;
        label = "Dispatch";
        modulation = "nfm";
        lowpass = -1;
        highpass = -1;
        notch = 192.80;
        ctcss = 192.80;
        bandwidth = 5000;
        outputs:
        (
          {
            type = "mixer";
            name = "SCC_Fire";
            balance = 1.0;
          }
        );
      },

```

**Comment by feelingwalnut** [comment]
ok, i've got this up and running except i forgot the ctcss frequency, i'll have to reaquire that and will test. until then i'm just running this build as i'd ran the priors

**Comment by rough316** [comment]
Having issues building...

Scanning dependencies of target hello_fft
[  4%] Building CXX object src/hello_fft/CMakeFiles/hello_fft.dir/mailbox.c.o
In file included from /home/pi/rtl_ctss/RTLSDR-Airband/src/hello_fft/mailbox.c:28:
/home/pi/rtl_ctss/RTLSDR-Airband/src/hello_fft/../rtl_airband.h:33:10: fatal error: config.h: No such file or directory
 #include "config.h"
          ^~~~~~~~~~
compilation terminated.
make[2]: *** [src/hello_fft/CMakeFiles/hello_fft.dir/build.make:63: src/hello_fft/CMakeFiles/hello_fft.dir/mailbox.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:171: src/hello_fft/CMakeFiles/hello_fft.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by charlie-foxtrot** [comment]
@rough316 what `cmake` options are you using and what hardware are you building on?  `hello_fft` should only be built if you're using a rpi with that hardware support

**Comment by rough316** [comment]
cmake -DNFM=ON -DPLATFORM=rpiv2 -DSOAPYSDR=ON -DRTLSDR=OFF ../

PI 3B+

**Comment by charlie-foxtrot** [comment]
PI 3B+ doesn't have the Broadcom Videocore 3 support that is enabled by setting platform to `rpiv2`.  Try instead using `-DPLATFORM=native`

**Comment by rough316** [comment]
cmake -DNFM=ON -DPLATFORM=native -DSOAPYSDR=ON -DRTLSDR=OFF ../

-- Checking for module 'fftw3f'
--   No package 'fftw3f' found
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:493 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:677 (_pkg_check_modules_internal)
  src/CMakeLists.txt:223 (pkg_check_modules)

**Comment by charlie-foxtrot** [comment]
@rough316 if you haven’t compiled form source before, check the instructions in the wiki that includes dependencies.

**Comment by charlie-foxtrot** [comment]
closing this for #368

**Pull request closed without merging**
