### PR TITLE
Add CTCSS support, second attempt

### PR DESCRIPTION
**Pull request by charlie-foxtrot**
Same changes as #366 but including unit tests

### CODE REVIEW

**Comment by charlie-foxtrot** [comment]
@rough316 @feelingwalnut if you could switch to this branch for testing I would appreciate it as this will be the code that merges (functionally equivalent to the other branch)

**Comment by feelingwalnut** [comment]
> @rough316 @feelingwalnut if you could switch to this branch for testing I would appreciate it as this will be the code that merges (functionally equivalent to the other branch)


git checkout add_ctcss_second_attempt
or unstable
?

**Comment by charlie-foxtrot** [comment]
```
git fetch
git checkout add_ctcss_second_attempt
```

**Comment by feelingwalnut** [comment]
compiled and running.
wish there was a solution for digital code squelch.

**Pull request merged**
